# Generated by Django 6.0.2 on 2026-03-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('estado_logico', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pelicula',
            },
        ),
        migrations.CreateModel(
            name='SalaCine',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sala_cine',
            },
        ),
        migrations.CreateModel(
            name='PeliculaSalaCine',
            fields=[
                ('id_pelicula_sala', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_pelicula', models.ForeignKey(db_column='id_pelicula', on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
                ('id_sala_cine', models.ForeignKey(db_column='id_sala_cine', on_delete=django.db.models.deletion.CASCADE, to='api.salacine')),
            ],
            options={
                'db_table': 'pelicula_salacine',
            },
        ),
    ]
